<?php

namespace App\Domain\Audit\Enums;

/**
 * Audited actions (master doc §27). Stored as the string value; never rename a case.
 * Later phases add their own cases (START_SHIFT, CREATE_TRANSACTION, PAYMENT_PAID, ...).
 */
enum AuditAction: string
{
    // Authentication
    case LOGIN = 'LOGIN';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case LOGOUT = 'LOGOUT';
    case TOKEN_REFRESHED = 'TOKEN_REFRESHED';
    case REFRESH_TOKEN_REUSE_DETECTED = 'REFRESH_TOKEN_REUSE_DETECTED';

    // User administration
    case USER_CREATED = 'USER_CREATED';
    case USER_CHANGED = 'USER_CHANGED';
    case USER_STATUS_CHANGED = 'USER_STATUS_CHANGED';
    case USER_ROLES_CHANGED = 'USER_ROLES_CHANGED';
    case USER_PASSWORD_RESET = 'USER_PASSWORD_RESET';

    // Access control configuration
    case ROLE_PERMISSIONS_SYNCED = 'ROLE_PERMISSIONS_SYNCED';

    // Master data (Phase 2)
    case LOCATION_CREATED = 'LOCATION_CREATED';
    case LOCATION_CHANGED = 'LOCATION_CHANGED';
    case LOCATION_STATUS_CHANGED = 'LOCATION_STATUS_CHANGED';
    case ATTENDANT_REGISTERED = 'ATTENDANT_REGISTERED';
    case ATTENDANT_CHANGED = 'ATTENDANT_CHANGED';
    case ATTENDANT_STATUS_CHANGED = 'ATTENDANT_STATUS_CHANGED';
    case DEVICE_REGISTERED = 'DEVICE_REGISTERED';
    case DEVICE_APPROVED = 'DEVICE_APPROVED';
    case DEVICE_REVOKED = 'DEVICE_REVOKED';
    case DEVICE_MARKED_LOST = 'DEVICE_MARKED_LOST';
    case ASSIGNMENT_CREATED = 'ASSIGNMENT_CREATED';
    case ASSIGNMENT_ENDED = 'ASSIGNMENT_ENDED';
    case ASSIGNMENT_CANCELLED = 'ASSIGNMENT_CANCELLED';
    case TARIFF_CREATED = 'TARIFF_CREATED';
    case TARIFF_CHANGED = 'TARIFF_CHANGED';
    case TARIFF_APPROVED = 'TARIFF_APPROVED';
    case TARIFF_REJECTED = 'TARIFF_REJECTED';

    // Operations (Phase 3)
    case START_SHIFT = 'START_SHIFT';
    case END_SHIFT = 'END_SHIFT';
    case SHIFT_FORCE_CLOSED = 'SHIFT_FORCE_CLOSED';
    case SHIFT_FLAGGED = 'SHIFT_FLAGGED';
    case SETTING_CHANGED = 'SETTING_CHANGED';

    // Transactions & cash (Phase 4)
    case CREATE_TRANSACTION = 'CREATE_TRANSACTION';
    case VOID_REQUESTED = 'VOID_REQUESTED';
    case VOID_APPROVED = 'VOID_APPROVED';
    case VOID_REJECTED = 'VOID_REJECTED';
    case CASH_BALANCES_REBUILT = 'CASH_BALANCES_REBUILT';

    // Payments / QRIS (Phase 6)
    case PAYMENT_CREATED = 'PAYMENT_CREATED';
    case PAYMENT_PAID = 'PAYMENT_PAID';
    case PAYMENT_LATE_PAID = 'PAYMENT_LATE_PAID';
    case PAYMENT_EXPIRED = 'PAYMENT_EXPIRED';
    case PAYMENT_FAILED = 'PAYMENT_FAILED';
    case PAYMENT_CANCELLED = 'PAYMENT_CANCELLED';
    case PAYMENT_CANCEL_REQUESTED = 'PAYMENT_CANCEL_REQUESTED';
    case PAYMENT_AMOUNT_MISMATCH = 'PAYMENT_AMOUNT_MISMATCH';
    case MANUAL_REFUND_RECORDED = 'MANUAL_REFUND_RECORDED';

    // Cash settlements (Phase 7)
    case SETTLEMENT_SUBMITTED = 'SETTLEMENT_SUBMITTED';
    case SETTLEMENT_VERIFIED = 'SETTLEMENT_VERIFIED';
    case SETTLEMENT_REJECTED = 'SETTLEMENT_REJECTED';
    case SETTLEMENT_CANCELLED = 'SETTLEMENT_CANCELLED';

    // Reconciliation (Phase 8)
    case RECONCILIATION_RUN = 'RECONCILIATION_RUN';

    // Review queue (Phase 9)
    case ANOMALY_REVIEWED = 'ANOMALY_REVIEWED';

    // Reports (Phase 10)
    case REPORT_EXPORT_REQUESTED = 'REPORT_EXPORT_REQUESTED';
    case REPORT_EXPORT_DOWNLOADED = 'REPORT_EXPORT_DOWNLOADED';
}
