<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Juru parkir registry (master doc §8.1). Each attendant has exactly one ATTENDANT login account.
 * attendant_code is generated by the server (JP-000001, ...) and doubles as the login username.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('parking_attendants', function (Blueprint $table) {
            $table->id();
            $table->string('attendant_code', 20)->unique();
            $table->foreignId('user_id')->unique()->constrained('users')->restrictOnDelete();
            $table->string('name', 150);
            $table->char('identity_number', 16)->unique();
            $table->string('phone', 20);
            $table->string('photo_path', 255)->nullable();
            $table->string('status', 20)->default('ACTIVE');
            $table->date('registered_at');
            $table->date('expired_at')->nullable();
            $table->timestampsTz();

            $table->index('status');
        });

        DB::statement(<<<'SQL'
            ALTER TABLE parking_attendants
                ADD CONSTRAINT parking_attendants_code_format_check CHECK (attendant_code ~ '^JP-[0-9]{6,}$'),
                ADD CONSTRAINT parking_attendants_nik_format_check CHECK (identity_number ~ '^[0-9]{16}$'),
                ADD CONSTRAINT parking_attendants_phone_format_check CHECK (phone ~ '^\+?[0-9]{8,15}$'),
                ADD CONSTRAINT parking_attendants_status_check CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'EXPIRED')),
                ADD CONSTRAINT parking_attendants_validity_check CHECK (expired_at IS NULL OR expired_at >= registered_at)
            SQL);

        // Owned by the column, so dropping the table (migrate:fresh, rollback) drops the sequence too.
        DB::statement('CREATE SEQUENCE parking_attendant_code_seq START 1 OWNED BY parking_attendants.attendant_code');
    }

    public function down(): void
    {
        Schema::dropIfExists('parking_attendants');
        DB::statement('DROP SEQUENCE IF EXISTS parking_attendant_code_seq');
    }
};
